### ISSUE TITLE
Kubeapps up fails in a default GKE cluster

### ISSUE THREAD

**Issue by arapulido** [kubeapps/installer#24]
Steps to reproduce:

1. Build a default GKE cluster with `gcloud container clusters create my-cluster`
2. Run ./kubeapps up

You get the following error:

```
ERRO[0009] Error updating clusterroles kubeless-controller-deployer: clusterroles.rbac.authorization.k8s.io "kubeless-controller-deployer" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["patch"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["patch"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["create"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["get"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["delete"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["list"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["update"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["patch"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["create"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["delete"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["update"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["patch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["functions"], APIGroups:["k8s.io"], Verbs:["get"]} PolicyRule{Resources:["functions"], APIGroups:["k8s.io"], Verbs:["list"]} PolicyRule{Resources:["functions"], APIGroups:["k8s.io"], Verbs:["watch"]}] user=&{apulido@gmail.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
```

**Comment by carlosrdrz** [comment]
From [RBAC GKE docs](https://cloud.google.com/container-engine/docs/role-based-access-control):
> Once the cluster has the legacy authorizer disabled, you must grant your user the ability to create authorization roles by running the following Kubernetes command:
> ```kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin [--user=<user-name>]```

As far as I know, this only happens when you enable RBAC and disable the legacy authorization in GKE, but from GKE 1.8, that is the default configuration.

Also, in order to run the command above, you need to have the `container.clusterRoleBindings.create` permission on GKE. That permission is included on the roles "Container Engine Admin" and "Owner".

That means that, if we assume the user has one of the roles mentioned above (e.g. she is the GCP project owner) we could run the command above when doing `kubeapps up` before pushing all the manifests and that should fix the issue.

Another option would be to list the permissions that `kubeapps up` needs somewhere, and let the users know they need those permissions on their accounts for it to work. The downside is that it won't be a one-command install anymore in that case.

**Comment by arapulido** [comment]
I agree that we should run the command (instead of documenting), and only document that you need to be a "Container Engine Admin" or "Owner" to run `kubeapps up`, which is not a crazy thing to ask.

**Comment by ngtuna** [comment]
Hmmm, even I created clusterrolebinding to bind my account to `cluster-admin` clusterrole, the error is still there. 

To be clear, with the `cluster-admin` power, my account could create a clusterrolebinding, but couldn't create a clusterrole.

**Comment by arapulido** [comment]
@carlosrdrz I see the same as @ngtuna . I am able to run the command in my personal account cluster (where I am an owner) and I get the same error. Any ideas?

**Comment by ngtuna** [comment]
I got it. That's so funny that GKE capitalize the email at the first letter. So gcloud says:

```
$ gcloud info | grep Account
Account: [ng.tuna@gmail.com]
```
But actually GKE recognize the user = Ng.tuna@gmail.com

**Comment by ngtuna** [comment]
But I am not sure if you got the same case @arapulido . This guy got different result with email: https://github.com/coreos/prometheus-operator/issues/357#issuecomment-333273392

**Comment by arapulido** [comment]
@ngtuna not sure I understand how you solved the issue. How did you run the command in the end?

**Comment by ngtuna** [comment]
@arapulido Well the user account detection from GKE confuses me. However I could pass it with the command @carlosrdrz gave us but the user info I caught from the error message. So in your case, this command should work it out:

```
$ kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=apulido@gmail.com
```

//The user info I caught from your error message above.

**Comment by ngtuna** [comment]
For the reference, here is my error message:

```
Error from server (Forbidden): error when creating "a.txt": clusterroles.rbac.authorization.k8s.io "kubeless-controller-deployer" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["patch"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["patch"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["create"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["get"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["delete"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["list"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["update"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["patch"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["create"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["delete"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["update"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["patch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["functions"], APIGroups:["k8s.io"], Verbs:["get"]} PolicyRule{Resources:["functions"], APIGroups:["k8s.io"], Verbs:["list"]} PolicyRule{Resources:["functions"], APIGroups:["k8s.io"], Verbs:["watch"]}] user=&{Ng.tuna@gmail.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
```
